var JSON = {
  "url" : "www.baidu.com",
  "data":[
  {
  	"blockid" : "1",
  	"img"  : "images/1.jpg",
  	"name" : "连衣裙1",
  	"ju" : "images/bao.png",
  	"oldPrace" : "￥255",
  	"juPrace" : "￥180",
  },
  {
  	"blockid" : "2",
  	"img"  : "images/2.jpg",
  	"name" : "连衣裙2",
  	"ju" : "images/bao.png",
  	"oldPrace" : "￥255",
  	"juPrace" : "￥180",
  },
  {
  	"blockid" : "3",
  	"img"  : "images/3.jpg",
  	"name" : "连衣裙3",
  	"ju" : "images/bao.png",
  	"oldPrace" : "￥255",
  	"juPrace" : "￥180",
  },
  {
  	"blockid" : "4",
  	"img"  : "images/4.jpg",
  	"name" : "连衣裙4",
  	"ju" : "images/bao.png",
  	"oldPrace" : "￥255",
  	"juPrace" : "￥180",
  },
  {
  	"blockid" : "5",
  	"img"  : "images/5.jpg",
  	"name" : "连衣裙5",
  	"ju" : "images/bao.png",
  	"oldPrace" : "￥255",
  	"juPrace" : "￥180",
  },
  {
  	"blockid" : "6",
  	"img"  : "images/6.jpg",
  	"name" : "连衣裙6",
  	"ju" : "images/bao.png",
  	"oldPrace" : "￥255",
  	"juPrace" : "￥180",
  },
  {
  	"blockid" : "7",
  	"img"  : "images/7.jpg",
  	"name" : "连衣裙7",
  	"ju" : "images/bao.png",
  	"oldPrace" : "￥255",
  	"juPrace" : "￥180",
  },
  {
  	"blockid" : "8",
  	"img"  : "images/8.jpg",
  	"name" : "连衣裙8",
  	"ju" : "images/bao.png",
  	"oldPrace" : "￥255",
  	"juPrace" : "￥180",
  },
  {
  	"blockid" : "9",
  	"img"  : "images/9.jpg",
  	"name" : "连衣裙9",
  	"ju" : "images/bao.png",
  	"oldPrace" : "￥255",
  	"juPrace" : "￥180",
  },
  {
  	"blockid" : "10",
  	"img"  : "images/10.jpg",
  	"name" : "连衣裙10",
  	"ju" : "images/bao.png",
  	"oldPrace" : "￥255",
  	"juPrace" : "￥180",
  },
 ]
}